export const BASE_URL = 'v1/portal/'
export const LOGIN_URL = 'auth/login/'
export const USER_PROFIL_URL = 'users/profile'
export const REGISTER_URL = 'auth/register'
export const CLASS_LIST_URL = 'schedules'
export const ROOM_LIST_URL = 'rooms'
export const SUBMIT_ROOM_URL = 'rooms'
export const SUBMIT_CLASS_URL = 'rooms'